pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build step not required for HTML'
            }
        }

        stage('Test') {
            steps {
                echo 'Checking if index.html exists...'
                bat 'dir'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                bat 'echo Deployment Successful'
            }
        }
    }
}
