pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build step not required for HTML'
            }
        }

        stage('Test') {
            steps {
                echo 'Checking if index.html exists...'
                sh 'ls -l'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'echo Deployment Successful'
            }
        }
    }
}
