pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Build step not required for HTML'
            }
        }

        stage('Test') {
            steps {
                echo 'Checking files...'
                sh 'ls -R'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying HTML app...'
                sh '''
                cp Jenkine-project/app/index.html /var/www/html/index.html
                '''
            }
        }
    }
}
